apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-worker
  # namespace: redis-cluster-system
  labels:
    name: redis-worker
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379
    nodePort: 32100
  selector:
    name: redis-cluster-worker
